# Generated by Django 5.2.8 on 2025-12-10 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name (required)', max_length=255)),
                ('phone', models.CharField(help_text='10-digit phone number (required)', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be 10 digits', regex='^[0-9]{10}$')])),
                ('address', models.CharField(help_text='Residential address (required)', max_length=255)),
                ('region', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], help_text='Region (required)', max_length=100)),
                ('is_registered', models.BooleanField(default=True, help_text='Account registration status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
