# Generated by Django 5.2.8 on 2026-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='officer_pics/'),
        ),
    ]
