# Generated by Django 5.2.8 on 2025-12-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        ('officers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='reported', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], default='central', max_length=50)),
                ('category', models.CharField(choices=[('water', 'Water Supply'), ('road', 'Road & Infrastructure'), ('electricity', 'Electricity'), ('sanitation', 'Sanitation'), ('other', 'Other')], default='other', max_length=50)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='complaint_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.citizen')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assigned_complaints', to='contractors.contractor')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_assigned_complaints', to='officers.officer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
