# Generated by Django 5.2.8 on 2026-01-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='region',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], max_length=50),
        ),
    ]
