# Generated by Django 5.2.8 on 2026-01-14 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
