# Generated by Django 5.2.8 on 2026-01-14 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_tracking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
