# Generated by Django 5.2.8 on 2026-01-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaint_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_proofs/'),
        ),
    ]
