# Generated by Django 5.2.8 on 2026-01-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_completion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='officer_feedback',
            field=models.TextField(blank=True, help_text='Officer feedback when work is rejected.', null=True),
        ),
    ]
