# Generated by Django 5.2.8 on 2025-12-10 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name (required)', max_length=255)),
                ('email', models.EmailField(help_text='Valid email address (required)', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='10-digit phone number (required)', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be 10 digits', regex='^[0-9]{10}$')])),
                ('company_name', models.CharField(help_text='Company name (required)', max_length=255)),
                ('specialization', models.CharField(help_text='Area of expertise (required)', max_length=255)),
                ('license_number', models.CharField(help_text='License number (required, must be unique)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status by officer', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when approved', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Officer who approved this contractor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contractors', to='officers.officer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
