# Generated by Django 5.2.8 on 2025-12-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='region',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], default='west', help_text='Service region (required)', max_length=50),
            preserve_default=False,
        ),
    ]
