# Generated by Django 5.2.8 on 2026-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_contractor_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='contractor_logos/'),
        ),
    ]
