"""
Django settings for urbanwatch project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url
import platform

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*'] #allow all hosts during development, change this in production.


# Application definition

INSTALLED_APPS = [

    #default apps.
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', #required for allauth.  # <--- Add this
    'cloudinary_storage', #for handling media files with cloudinary.
    'cloudinary', #for handling media files with cloudinary.
    'storages', #for handling media files with cloudinary.

    #third party apps.
    'crispy_forms',
    'crispy_tailwind',
    'tailwind',
    'theme',

    #my apps.
    'accounts',
    'complaints',
    'users',
    'officers',
    'contractors',
    

    #allauth apps.
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", #for serving static files in production.
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', #allauth middleware.

]

ROOT_URLCONF = 'urbanwatch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], #for project wide templates.
        'APP_DIRS': True, #this enables django to look in app/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media', #to handle media files
            ],
        },
    },
]

WSGI_APPLICATION = 'urbanwatch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Use SQLite locally (if no DATABASE_URL is found)
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#tailwind css settings
TAILWIND_APP_NAME = 'theme'
if platform.system() == 'Windows':
    NPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd'
else:
    NPM_BIN_PATH = 'npm'
CRISPY_ALLOWED_TEMPLATE_PACKS = ["tailwind"]
CRISPY_TEMPLATE_PACK = "tailwind"

#media files settings.
#DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
if DEBUG:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / "media"

else:
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        }
    }
"""STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}"""

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config( 
  cloud_name = config('CLOUD_NAME', default=''), 
  api_key = config('CLOUDINARY_API_KEY', default=''), 
  api_secret = config('CLOUDINARY_API_SECRET', default=''),
  secure = True
)

# Tell Django to use Cloudinary for uploaded media
# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
    'SECURE': True,  # Documentation says HTTPS is default, but we force it to be safe
    'MEDIA_TAG': 'urbanwatch_media',
}

#Allauth settings.
SITE_ID = 1

LOGIN_URL = 'account_login'
LOGOUT_REDIRECT_URL = '/' #go back to login page after logout.
LOGIN_REDIRECT_URL = '/' #Will be overriden by the adapter.
ACCOUNT_SIGNUP_REDIRECT_URL = 'account_login' #citizen will go to login page after signup. 

ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'
ACCOUNT_LOGOUT_ON_GET = True #logout immediatly without confrimation page(optional but smoother). 

ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = False
#ACCOUNT_SIGNUP_EMAIL_REQUIRED = False

#use custom signup form (CitizenSignupForm)
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CitizenSignupForm',
}

# ==========================================
# EMAIL SETTINGS (Gmail SMTP)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# REPLACE THIS with your actual Gmail address
EMAIL_HOST_USER = config('EMAIL_HOST_USER') 

EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = 'UrbanWatch+ Team <urbanwatchplus@gmail.com>'


"""# Add this temporarily to see errors in the log
import logging
logging.getLogger('cloudinary').setLevel(logging.DEBUG)"""